/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const angular_size_gate: (a: number) => number;
export const apparent_altitude: (a: number, b: number) => number;
export const apparent_altitude_k: (a: number, b: number, c: number) => number;
export const apparent_angular_diameter_deg: (a: number, b: number, c: number) => number;
export const comfort_factor: (a: number, b: number) => number;
export const computeRooftopLayer: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number) => [number, number];
export const computeSightlineProfile: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number) => [number, number];
export const computeViewshed: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number) => [number, number];
export const curvature_drop: (a: number) => number;
export const curvature_drop_k: (a: number, b: number) => number;
export const elevationBilinear: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => number;
export const elevation_angle_deg: (a: number, b: number) => number;
export const elevation_score: (a: number) => number;
export const eyeHeight: () => number;
export const fraction_visible: (a: number, b: number, c: number) => number;
export const intersectSegmentBuildingFlat: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const is_blocked: (a: number) => number;
export const projectLatLngLat: (a: number, b: number, c: number, d: number) => number;
export const projectLatLngLng: (a: number, b: number, c: number, d: number) => number;
export const projectLocalX: (a: number, b: number, c: number, d: number) => number;
export const projectLocalY: (a: number, b: number, c: number, d: number) => number;
export const roundtripBuildings: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const roundtripTerrain: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const score: (a: number, b: number, c: number, d: number, e: number, f: number) => number;
export const visibility_category: (a: number, b: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
